import type { Metadata } from "next";
import "./globals.css";
import BaseLayout from "../components/Layout/BaseLayout";
import localFont from "next/font/local";

const manrope = localFont({
  src: [
    {
      path: "./fonts/Manrope-Medium.ttf",
      weight: "500",
      style: "semibold",
    },
    {
      path: "./fonts/Manrope-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Manrope-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-manrope",
  // display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={manrope.variable}
      >
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
